### ISSUE TITLE
test error for 5.x  api_anomalies_integration_test.go:23: error unpacking anomaly 

### ISSUE THREAD

**Issue by bwJuniper** [Juniper/apstra-go-sdk#365]
- json: cannot unmarshal number into Go struct field .identity.item_id of type apstra.ObjectId

**Comment by rajagopalans** [comment]
We should probably cut this code out. This was written for a VMWare integration that is currently not being used anyway.

**Comment by chrismarget-j** [comment]
We'll solve this with #366
