### ISSUE TITLE
Test IBA Predefined Probes fails for Apstra 5.x

### ISSUE THREAD

**Issue by bwJuniper** [Juniper/apstra-go-sdk#376]
=== RUN   TestIbaPredefinedProbes
2024/09/16 16:54:37 testing Predefined Probes against slicer zz-bwester-ai_scale.small.2485377892354-3673941566 (5.0.0-a-6)
    api_iba_predefined_probes_test.go:40: Try an obviously fake name : FAKE
    api_iba_predefined_probes_test.go:45: no Predefined Probe with name 'FAKE' found
    api_iba_predefined_probes_test.go:49: Get Predefined Probe By Name bandwidth_utilization
    api_iba_predefined_probes_test.go:54: Generate a probe to calculate bandwidth utilization.
        
        This probe captures history of bandwidth utilization trends at differing
        levels of aggregation.
    api_iba_predefined_probes_test.go:55: [123 34 116 121 112 101 34 58 32 34 111 98 106 101 99 116 34 44 32 34 112 114 111 112 101 114 116 105 101 115 34 58 32 123 34 108 97 98 101 108 34 58 32 123 34 116 105 116 108 101 34 58 32 34 80 114 111 98 101 32 76 97 98 101 108 34 44 32 34 116 121 112 101 34 58 32 34 115 116 114 105 110 103 34 44 32 34 109 105 110 76 101 110 103 116 104 34 58 32 49 44 32 34 109 97 120 76 101 110 103 116 104 34 58 32 49 50 48 44 32 34 100 101 102 97 117 108 116 34 58 32 34 66 97 110 100 119 105 100 116 104 32 85 116 105 108 105 122 97 116 105 111 110 34 125 44 32 34 102 105 114 115 116 95 115 117 109 109 97 114 121 95 97 118 101 114 97 103 101 95 112 101 114 105 111 100 34 58 32 123 34 116 105 116 108 101 34 58 32 34 70 105 114 115 116 32 115 117 109 109 97 114 121 32 97 118 101 114 97 103 101 32 112 101 114 105 111 100 34 44 32 34 116 121 112 101 34 58 32 34 105 110 116 101 103 101 114 34 44 32 34 109 105 110 105 109 117 109 34 58 32 49 44 32 34 100 101 102 97 117 108 116 34 58 32 49 50 48 125 44 32 34 102 105 114 115 116 95 115 117 109 109 97 114 121 95 116 111 116 97 108 95 100 117 114 97 116 105 111 110 34 58 32 123 34 116 105 116 108 101 34 58 32 34 70 105 114 115 116 32 115 117 109 109 97 114 121 32 104 105 115 116 111 114 121 32 100 117 114 97 116 105 111 110 34 44 32 34 116 121 112 101 34 58 32 34 105 110 116 101 103 101 114 34 44 32 34 109 105 110 105 109 117 109 34 58 32 49 44 32 34 100 101 102 97 117 108 116 34 58 32 51 54 48 48 125 44 32 34 115 101 99 111 110 100 95 115 117 109 109 97 114 121 95 97 118 101 114 97 103 101 95 112 101 114 105 111 100 34 58 32 123 34 116 105 116 108 101 34 58 32 34 83 101 99 111 110 100 32 115 117 109 109 97 114 121 32 97 118 101 114 97 103 101 32 112 101 114 105 111 100 34 44 32 34 116 121 112 101 34 58 32 34 105 110 116 101 103 101 114 34 44 32 34 109 105 110 105 109 117 109 34 58 32 49 44 32 34 100 101 102 97 117 108 116 34 58 32 51 54 48 48 125 44 32 34 115 101 99 111 110 100 95 115 117 109 109 97 114 121 95 116 111 116 97 108 95 100 117 114 97 116 105 111 110 34 58 32 123 34 116 105 116 108 101 34 58 32 34 83 101 99 111 110 100 32 115 117 109 109 97 114 121 32 104 105 115 116 111 114 121 32 100 117 114 97 116 105 111 110 34 44 32 34 116 121 112 101 34 58 32 34 105 110 116 101 103 101 114 34 44 32 34 109 105 110 105 109 117 109 34 58 32 49 44 32 34 100 101 102 97 117 108 116 34 58 32 50 53 57 50 48 48 48 125 125 44 32 34 97 100 100 105 116 105 111 110 97 108 80 114 111 112 101 114 116 105 101 115 34 58 32 102 97 108 115 101 125]
    api_iba_predefined_probes_test.go:57: Instantiating Probe bandwidth_utilization
    api_iba_predefined_probes_test.go:72: Got back Probe Id 93acb974-f326-43da-ac69-d8fbfd076606 
         Now Make a Widget with it.
    api_iba_predefined_probes_test.go:81: {"errors": "Url not found"} - http response '404 NOT FOUND' at 'https://10.28.57.3:443/api/blueprints/83900a8b-4277-492d-a878-8d9454f6f7c2/iba/widgets?async=full'
--- FAIL: TestIbaPredefinedProbes (8.02s)

**Comment by chrismarget-j** [comment]
Closed by #396
