### ISSUE TITLE
Test CRUD IBA Dashboards fails Apstra v5.x

### ISSUE THREAD

**Issue by bwJuniper** [Juniper/apstra-go-sdk#377]
api_iba_dashboards_test.go:32: 
        	Error Trace:	/Users/bwester/GolandProjects/apstra-go-sdk/apstra/helpers_test.go:648
        	            				/Users/bwester/GolandProjects/apstra-go-sdk/apstra/api_iba_dashboards_test.go:32
        	Error:      	Received unexpected error:
        	            	{"errors": {"Label": "Unknown field", "Duration": "Unknown field", "Threshold": "Unknown field"}} - http response '422 UNPROCESSABLE ENTITY' at 'https://10.28.57.3:443/api/blueprints/851464a5-5d19-433b-9de4-e91c185aa99c/iba/predefined-probes/bgp_session?async=full'
        	Test:       	TestCreateReadUpdateDeleteIbaDashboards/5.0.0-a-6_zz-bwester-ai_scale.small.2485377892354-3673941566
--- FAIL: TestCreateReadUpdateDeleteIbaDashboards/5.0.0-a-6_zz-bwester-ai_scale.small.2485377892354-3673941566 (6.56s)

**Comment by chrismarget-j** [comment]
Closed by #398
