### ISSUE TITLE
TestIbaProbes specific_interface_flapping fails

### ISSUE THREAD

**Issue by bwJuniper** [Juniper/apstra-go-sdk#378]
=== CONT  TestIbaProbes/5.0.0-a-6_zz-bwester-ai_scale.small.2485377892354-3673941566/specific_interface_flapping
    api_iba_probes_test.go:380: Get Predefined Probe By Name specific_interface_flapping
    api_iba_probes_test.go:384: Instantiating Probe specific_interface_flapping
    api_iba_probes_test.go:391: 
        	Error Trace:	/Users/bwester/GolandProjects/apstra-go-sdk/apstra/api_iba_probes_test.go:391
        	Error:      	An error is expected but got nil.
        	Test:       	TestIbaProbes/5.0.0-a-6_zz-bwester-ai_scale.small.2485377892354-3673941566/specific_interface_flapping
--- FAIL: TestIbaProbes/5.0.0-a-6_zz-bwester-ai_scale.small.2485377892354-3673941566/specific_interface_flapping (0.74s)

**Comment by chrismarget-j** [comment]
Closed by #396
